# Generated by Django 5.0 on 2024-01-30 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_core', '0002_assetsdb_delete_user_account_delete_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsdb',
            name='file',
        ),
    ]
