# Generated by Django 5.0 on 2024-01-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_core', '0003_remove_assetsdb_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsdb',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
