# Generated by Django 5.0 on 2024-01-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_core', '0005_remove_assetsdb_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsdb',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
