# Generated by Django 5.0 on 2024-01-30 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_core', '0006_assetsdb_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsdb',
            name='file_name',
        ),
    ]
