# Generated by Django 5.0 on 2024-01-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_core', '0007_remove_assetsdb_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsdb',
            name='file',
        ),
        migrations.AddField(
            model_name='assetsdb',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
